# Generated by Django 4.2.7 on 2023-12-05 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='skill',
        ),
    ]
