# Generated by Django 4.2.7 on 2023-12-06 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userprofile_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='skill',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=20, null=True),
        ),
    ]
